### PR TITLE
Make TypeScript types more granular

### PR DESCRIPTION
**Pull request by macalinao**
Adds types which are based on `Idl`. Theoretically these shouldn't be breaking, as they extend the original types.

### CODE REVIEW

**Comment by macalinao** [comment]
Note: these should be tested first against existing programs

**Comment by armaniferrante** [comment]
> Note: these should be tested first against existing programs

The tests run by CI should be a reasonably sufficient check.

**Comment by fanatid** [comment]
@macalinao PR with conflicts resolving: https://github.com/saber-hq/anchor/pull/2

It would be great to see these types in anchor!

**Comment by armaniferrante** [comment]
> @macalinao PR with conflicts resolving: [saber-hq#2](https://github.com/saber-hq/anchor/pull/2)
> 
> It would be great to see these types in anchor!

Agreed! Just needs some testing before merging.

**Comment by macalinao** [comment]
Moved to https://github.com/project-serum/anchor/pull/537 .

**Pull request closed without merging**
