### PR TITLE
WILL IT RUN?

### PR DESCRIPTION
**Pull request by paul-schaaf**
just checking whether repo now runs pipelines when I do PRs. and it does!

### CODE REVIEW

**Comment by fanatid** [comment]
Checked actions, 
- We need to cache solana, otherwise we install it for each test and more.. :disappointed: 
- Can we try to add `--depth 1` to `git submodule update --init --recursive`?
- Maybe we need to cache `yarn build` result in `ts` folder because it's takes 20s for each item in matrix (20 items in total).

**Comment by armaniferrante** [comment]
I'm guessing your PRs weren't running against CI because your commits weren't signed. I disabled that feature for now, but you should enable commit signing :).

**Comment by paul-schaaf** [comment]
@fanatid 
we do cache solana. the github/actions/setup-solana/action.yaml is called in every job and caches the solana build. I'll add the other stuff!

**Comment by paul-schaaf** [comment]
@armaniferrante will do

**Comment by paul-schaaf** [comment]
closing this in favour of https://github.com/project-serum/anchor/pull/1074

**Comment by fanatid** [comment]
Indeed, sorry! I interpreted wrong CI logs :/

**Pull request closed without merging**
